name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Build + tests
        run: mvn -B clean verify

      - name: Build classpath for OpenJML
        run: mvn -q -DskipTests dependency:build-classpath -Dmdep.outputFile=cp.txt
        
      - name: OpenJML (download + verify)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip
          curl -L -o openjml.zip https://github.com/OpenJML/OpenJML/releases/download/v0.20.0/openjml.zip
          ls -lh openjml.zip
          unzip -q openjml.zip -d openjml

          mvn -q -DskipTests dependency:build-classpath -Dmdep.outputFile=cp.txt
          CP="target/classes:$(cat cp.txt)"

          openjml/*/openjml -version
          openjml/*/openjml -esc -classpath "$CP" src/main/java/tn/esprit/spring/services/SubscriptionServicesImpl.java

